# Generated by Django 6.0.4 on 2026-04-13 11:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('filieres', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(db_index=True, max_length=100, verbose_name='Prenom')),
                ('last_name', models.CharField(db_index=True, max_length=100, verbose_name='Nom')),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Telephone')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='students/photos/')),
                ('status', models.CharField(choices=[('actif', 'Actif'), ('suspendu', 'Suspendu'), ('diplome', 'Diplome')], db_index=True, default='actif', max_length=20)),
                ('date_inscription', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('filiere', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='filieres.filiere')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_inscription'],
                'indexes': [models.Index(fields=['last_name', 'first_name'], name='students_st_last_na_3e473b_idx'), models.Index(fields=['status', 'date_inscription'], name='students_st_status_e98435_idx')],
            },
        ),
    ]
